n = 3;
cvx_begin
    variable lambda(n)
    maximize (1/4 * (lambda(1)-lambda(2)+lambda(3))^2 ...
        + 1/4 * (lambda(3)+lambda(2))^2 ...
        + 1/2 * (-lambda(1)+lambda(2)-lacmbda(3)-6) * lambda(1) ...
        + 1/2 * (lambda(1)-2*lambda(2)+4) * lambda(2) ...
        + 1/2 * (lambda(1)+2*lambda(3)-4) * lambda(3) ...
    )
    subject to
        lambda(1) >= 0
        lambda(2) >= 0
        lambda(3) >= 0
cvx_end